pipeline{
    agent none
    
    stages{
        
        stage('Backend'){
            agent{
                docker { image 'maven:3.8.1-adoptopenjdk-11' }
            }
            steps{
                sh 'mvn --version'

                sh 'cp multi-stage-multi-agent/HelloWorld.java .'
                
                sh 'javac HelloWorld.java'

                sh 'java HelloWorld'
            }

        }

        stage('Frontend'){
            agent{
                docker { image 'node:16-alpine'}
            }
            steps{
                sh 'node --version'
            }
        }
    }
}
